name: DP-LegendaryEnderChest
version: 1.0.0.0
main: com.darksoldier1404.dlec.LegendaryEnderChest
api-version: 1.18
authors: [ DEAD_POOLIO_ ]
depend:
  - DPP-Core
commands:
  엔더창고:
    aliases: [dlec]
